"""firebase auth support

Revision ID: 2ec6bd92d612
Revises: 
Create Date: 2026-04-24 15:52:28.040220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '2ec6bd92d612'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_uid', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_column('users', 'firebase_uid')
    # ### end Alembic commands ###